cityapp/api/urls.py
from api.community_view import *
from api.user_views import *
from api.city_view import *
from django.urls import path
from rest_framework_swagger.views import get_swagger_view

schema_view = get_swagger_view(title='Community API')

app_name = "api"

urlpatterns = [
    path('users/register', UserRegistrationAPIView.as_view(), name="register"),
    path('users/login/', UserLoginAPIView.as_view(), name="login"),
    path('tokens/<key>/', UserTokenAPIView.as_view(), name="token"),

    path('community/swagger/', schema_view),

    path('community/create/', CreateCommunityAPIView.as_view(), name="create-community"),
    path('community/join/', JoinCommunityAPIView.as_view(), name="join-community"),
    path('community/search/', SearchCommunitiesAPIView.as_view(), name="search-community"),
    path('community/latest-posts/', UsersLatestPostsListAPIView.as_view(), name="latest-posts"),

    path('comment/create/', CommentCreateAPIView.as_view(), name="comment-create"),
    path('comment/create/<pk>/', CommentCreateAPIView_ForSpecificPost.as_view(), name="comment-create-post"),

    path('comment/list/', CommentListAPIView.as_view(), name="comment-list"),
    path('comment/list/<int:post_id>', CommentListAPIView_ForSpecificPost.as_view(), name="comment-list-specific"),

    path('comment/delete/<pk>/', CommentDeleteAPIView.as_view(), name="comment-delete"),
    path('comment/update/<pk>/', CommentUpdateAPIView.as_view(), name="comment-update"),
    path('search-city/', GetCityInformation.as_view(), name="search-city"),
    path('advanced-search/', AdvancedSearch.as_view(), name="advanced-search"),



]

cityapp/city/urls.py
from city.views import *
from django.urls import path

app_name = 'city'

urlpatterns = [
    path('list', ListCityAPIView.as_view(), name="list-city"),
    path('detail/<name>', ShowDetailedCityAPIView.as_view(), name="detail-city"),
    path('delete/<name>', DeleteCityAPIView.as_view(), name="delete-city"),
    path('update/<name>', UpdateCityAPIView.as_view(), name="update-city"),
    path('create/', CreateCityAPIView.as_view(), name="create-city"),
    path('allCities/', ListAllCitiesAPIView.as_view(), name="all-cities"),
]

cityapp/cityapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

api_urls = [
    path('community/', include('api.urls')),

]

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('community.urls')),
                  path('api/', include(api_urls)),
                  path('city/', include('city.urls')),
                  path('activity/', include('actstream.urls')),  # Activity Stream URL
                  path('api/annotations/', include('annotations.api.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cityapp/community/urls.py
from community import feeds
from community.views import *
from django.conf.urls import url
from django.urls import path

app_name = 'community'

urlpatterns = [
    path('', IndexTemplateView.as_view(), name="index"),
    path('search$', CommunitiesListTemplateView.as_view(), name="search-communities"),
    path('register', register_view, name="register"),
    path('login', login_view, name="login"),
    path('logout', logout_view, name="logout"),
    path('manager', CommunityLoginTemplateView.as_view(), name="manager"),
    path('dashboard', CommunityDashboardTemplateView.as_view(), name="dashboard"),
    path('communites-list', UserCommunitiesListTemplateView.as_view(), name="communities-list-user"),
    path('communities/<int:community_id>', CommunitiesDetailedTemplateView.as_view(), name="community-detail"),
    path('posts/<int:post_id>', PostsDetailedTemplateView.as_view(), name="post-detail"),
    path('data-types/<int:data_type_id>', DataTypeTemplateView.as_view(), name="data-type-detail"),
    path('communites-create', CreateCommunityTemplateView.as_view(), name="communities-create"),
    path('posts-create/<int:community_id>', CreatePostTemplateView.as_view(), name="posts-create"),
    path('data-type-create/<int:community_id>', CreateDataTypeTemplateView.as_view(), name="data-type-create"),
    path('join-community/<int:joined_community>', JoinCommunityTemplateView.as_view(), name="join-community"),
    path('joined-communites-list', JoinedCommunitiesListTemplateView.as_view(), name="joined-communities-list"),
    path('stream/json', feeds.UserJSONActivityFeed_V2.as_view(), name='actstream_feed_json'),
    path('stream/', notification, name='notification_combined'),
    path('stream/user/', notification_user, name='notification_user_all'),
    path('stream/community/', notification_community, name='notification_community_all'),
    path('stream/post', notification_post, name='notification_post_all'),
    path('stream/posttemplate', notification_posttemplate, name='notification_posttemplate_all'),
    path('followings/', followings, name='followings_combined'),
    path('followings/user/', followings_user, name='followings_user_all'),
    path('followings/community/', followings_community, name='followings_community_all'),
    path('followings/post/', followings_post, name='followings_post_all'),
    path('followings/posttemplate/', followings_post_template, name='followings_posttemplate_all'),
    path('followers/', followers, name='followers'),
    path('get-all-users', GetAllUsersTemplateView.as_view(), name="get-all-users"),
    path('flag-inappropriate', FlagPostAsInappropriate.as_view(), name="flag-post-inappropriate"),
    path('flag-appropriate', FlagPostAsAppropriate.as_view(), name="flag-post-appropriate"),
    path('user-posts/<int:user_id>', UserCreatedPostsTemplateView.as_view(), name="user-posts"),
    path('popularitems', PopularItems, name="popular_items"),
    path('popularitems/user', PopularItems_User, name="popular_items_user"),
    path('popularitems/community', PopularItems_Community, name="popular_items_community"),
    path('popularitems/posttemplate', PopularItems_PostTemplate, name="popular_items_posttemplate"),
    path('popularitems/post', PopularItems_Post, name="popular_items_post"),
    path('google587629e753de506e.html', GoogleVerify.as_view(), name="google-verify"),
    path('search', AdvancedSearchPage.as_view(), name="search-page"),
    path('delete-post/<int:post_id>', product_delete_rest_endpoint, name="delete-post"),
    # Override From <Actstream Url> In Order To Enable <User Stopped Following> Notification
    url(
        r'^unfollow/(?P<content_type_id>[^/]+)/(?P<object_id>[^/]+)/(?:(?P<flag>[^/]+)/)?$',
        follow_unfollow,
        {'do_follow': False},
        name='unfollow'
    ),
    url(
        r'^unfollow_all/(?P<content_type_id>[^/]+)/(?P<object_id>[^/]+)/(?:(?P<flag>[^/]+)/)?$',
        follow_unfollow,
        {'actor_only': False, 'do_follow': False},
        name='unfollow_all'
    )

]

cityapp/city/models.py
# Create your models here.
from community_user.models import CommunityUser
from django.db import models
from django.utils import timezone


class City(models.Model):
    created_by = models.ForeignKey(CommunityUser, related_name="city_author", on_delete=models.CASCADE, blank=True,
                                   null=True)
    name = models.CharField(max_length=55, unique=True)
    country_name = models.CharField(max_length=55)
    geolocation = models.CharField(max_length=55)
    image = models.ImageField(upload_to='media/city', null=True, blank=True)
    creation_date = models.DateTimeField(editable=False)
    modification_date = models.DateTimeField(editable=False)

    # Displaying city's name
    def __str__(self):
        return self.name

    # Creation Date and Modification Date while creating and update
    def save(self, *args, **kwargs):
        if not self.id:
            self.creation_date = timezone.now()
        self.modification_date = timezone.now()
        return super(City, self).save(*args, **kwargs)

# def save_city(sender, instance, **kwargs):
# to do --> action send


# post_save.connect(save_city, sender=City)

cityapp/city/views.py
# Create your views here.
import base64

from city.models import City
from city.serializers import CitySerializer
from community.models import Community
from django.core import serializers
from django.core.files.base import ContentFile
from django.http import JsonResponse
from rest_framework.generics import (ListAPIView,
                                     RetrieveAPIView,
                                     DestroyAPIView,
                                     UpdateAPIView,
                                     CreateAPIView, )
from rest_framework.renderers import TemplateHTMLRenderer
from rest_framework.response import Response


# Format for Uploading an image
def base64_file(data, name=None):
    _format, _img_str = data.split(';base64,')
    _name, ext = _format.split('/')
    if not name:
        name = _name.split(":")[-1]
    return ContentFile(base64.b64decode(_img_str), name='{}.{}'.format(name, ext))


# Listing all cities view
class ListCityAPIView(ListAPIView):
    renderer_classes = [TemplateHTMLRenderer]
    template_name = 'user/cities.html'
    serializer_class = CitySerializer

    def get(self, request):
        queryset = City.objects.all()
        my_communities = Community.objects.filter(joined_users=self.request.user)
        return Response({"cities": queryset, "communities": my_communities})


# Displaying Specific City View
class ShowDetailedCityAPIView(RetrieveAPIView):
    queryset = City.objects.all()
    serializer_class = CitySerializer
    lookup_field = 'name'

    renderer_classes = [TemplateHTMLRenderer]
    template_name = 'user/city.html'

    def get(self, request, name):
        city = City.objects.get(name=name)
        my_communities = Community.objects.filter(joined_users=self.request.user)
        communities = Community.objects.filter(city_id=city.id)

        return Response({'city': city, 'comms': communities, "communities": my_communities})


# Deleting city view (view not compleated):TODO
class DeleteCityAPIView(DestroyAPIView):
    queryset = City.objects.all()
    serializer_class = CitySerializer
    lookup_field = 'name'


# Updating city view (view page not compleated):TODO
class UpdateCityAPIView(UpdateAPIView):
    queryset = City.objects.all()
    serializer_class = CitySerializer
    lookup_field = 'name'


# Creating a new city view
class CreateCityAPIView(CreateAPIView):
    serializer_class = CitySerializer
    renderer_classes = [TemplateHTMLRenderer]
    template_name = 'user/create_city.html'

    def get(self, request):
        communities = Community.objects.filter(joined_users=self.request.user)
        queryset = City.objects.all()
        return Response({"cities": queryset, "communities": communities})

    def post(self, request):
        name = request.data["name"]
        country_name = request.data["country_name"]
        image = request.data["image"]
        if not name:
            return JsonResponse({"error": "City Name Can't be Empty"})
        try:
            city = City.objects.create(name=name, country_name=country_name, image=base64_file(image),
                                       created_by=request.user)
        except Exception as e:
            print(e)
            return JsonResponse({"error": "Error Creating the City"})

        return JsonResponse({"name": city.name})


class ListAllCitiesAPIView(RetrieveAPIView):
    serializer_class = CitySerializer

    def get(self, request):
        queryset = City.objects.all()
        cities_serialized = serializers.serialize('json', queryset)
        return JsonResponse({"cities": cities_serialized})

cityapp/templates/user/activity.html
{% extends "user/manager.html" %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
{% block head_css %}
    <style>
        .h-100 {
            height: auto !important;
        }

        #map {
            height: 400px; /* The height is 400 pixels */
            width: 100%; /* The width is the width of the web page */
        }
    </style>
{% endblock %}


{% block wrapper %}
    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h1 mb-0 text-gray-800">Notifications</h1>
        </div>
        <div class="d-sm-flex align-items-center">
            <h1 class="h4 mb-0 text-gray-800">From The People You Follow</h1>
            <a  href="{% url "community:notification_user_all" %}" class="h9 mb-0 text-gray-800"><i>&nbsp; (See All) </i></a>
        </div>
        <div class="row">
            {% load activity_tags %}
            {% if user_activities|length == 0 %}
                <div class="col-xl-3 col-md-6 mb-4">
                    <div class="card border-left-info shadow h-100 py-2">
                        <a href="{% url "community:popular_items" %}">
                        <div class="card-body">
                            <div class="row no-gutters align-items-center">
                                <div class="col mr-2">
                                    <div class="text-xs font-weight-bold text-info text-uppercase mb-1">You Do Not Have Any Notification</div>
                                    <div class="text-xs font-weight-bold text-info text-uppercase mb-1">Click Here To Find out Something Interesting</div>
                                </div>
                                <div class="col-auto">
                                    <i class="fas fa-clipboard-list fa-2x text-gray-300"></i>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% else %}
            {% for action in user_activities %}
                <div class="col-xl-3 col-md-6 mb-4">
                    <div class="card border-left-info shadow h-100 py-2">
                        <div class="card-body">
                            <div class="row no-gutters align-items-center">
                                <div class="col mr-2">
                                    <div class="text-xs font-weight-bold text-info text-uppercase mb-1" onclick="return false">{% display_action action %}</div>
                                </div>
                                <div class="col-auto">
                                    <i class="fas fa-clipboard-list fa-2x text-gray-300"></i>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
            {% endif %}

        </div>
    </div>

    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->
        <div class="d-sm-flex align-items-center">
            <h1 class="h4 mb-0 text-gray-800">From The Communities You Follow</h1>
            <a  href="{% url "community:notification_community_all" %}" class="h9 mb-0 text-gray-800"><i>&nbsp; (See All) </i></a>
        </div>
        <div class="row">
            {% if communitiy_activities|length == 0 %}
                <div class="col-xl-3 col-md-6 mb-4">
                    <div class="card border-left-info shadow h-100 py-2">
                        <a href="{% url "community:popular_items" %}">
                        <div class="card-body">
                            <div class="row no-gutters align-items-center">
                                <div class="col mr-2">
                                    <div class="text-xs font-weight-bold text-info text-uppercase mb-1">You Do Not Have Any Notification</div>
                                    <div class="text-xs font-weight-bold text-info text-uppercase mb-1">Click Here To Find out Something Interesting</div>
                                </div>
                                <div class="col-auto">
                                    <i class="fas fa-clipboard-list fa-2x text-gray-300"></i>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% else %}
            {% for action in communitiy_activities %}
                <div class="col-xl-3 col-md-6 mb-4">
                    <div class="card border-left-info shadow h-100 py-2">
                        <div class="card-body">
                            <div class="row no-gutters align-items-center">
                                <div class="col mr-2">
                                    <div class="text-xs font-weight-bold text-info text-uppercase mb-1" onclick="return false">{% display_action action %}</div>
                                </div>
                                <div class="col-auto">
                                    <i class="fas fa-clipboard-list fa-2x text-gray-300"></i>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
            {% endif %}
        </div>
    </div>

    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->
        <div class="d-sm-flex align-items-center">
            <h1 class="h4 mb-0 text-gray-800">From The Posts You Follow</h1>
            <a  href="{% url "community:notification_post_all" %}" class="h9 mb-0 text-gray-800"><i>&nbsp; (See All) </i></a>
        </div>
        <div class="row">
            {% if post_activities|length == 0 %}
                <div class="col-xl-3 col-md-6 mb-4">
                    <div class="card border-left-info shadow h-100 py-2">
                        <a href="{% url "community:popular_items" %}">
                        <div class="card-body">
                            <div class="row no-gutters align-items-center">
                                <div class="col mr-2">
                                    <div class="text-xs font-weight-bold text-info text-uppercase mb-1">You Do Not Have Any Notification</div>
                                    <div class="text-xs font-weight-bold text-info text-uppercase mb-1">Click Here To Find out Something Interesting</div>
                                </div>
                                <div class="col-auto">
                                    <i class="fas fa-clipboard-list fa-2x text-gray-300"></i>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% else %}
            {% for action in post_activities %}
                <div class="col-xl-3 col-md-6 mb-4">
                    <div class="card border-left-info shadow h-100 py-2">
                        <div class="card-body">
                            <div class="row no-gutters align-items-center">
                                <div class="col mr-2">
                                    <div class="text-xs font-weight-bold text-info text-uppercase mb-1" onclick="return false">{% display_action action %}</div>
                                </div>
                                <div class="col-auto">
                                    <i class="fas fa-clipboard-list fa-2x text-gray-300"></i>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
            {% endif %}
        </div>
    </div>


    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->
        <div class="d-sm-flex align-items-center">
            <h1 class="h4 mb-0 text-gray-800">From The Post Templates You Follow</h1>
            <a  href="{% url "community:notification_posttemplate_all" %}" class="h9 mb-0 text-gray-800"><i>&nbsp; (See All) </i></a>
        </div>
        <div class="row">
            {% if posttemplate_activities|length == 0 %}
                <div class="col-xl-3 col-md-6 mb-4">
                    <div class="card border-left-info shadow h-100 py-2">
                        <a href="{% url "community:popular_items" %}">
                        <div class="card-body">
                            <div class="row no-gutters align-items-center">
                                <div class="col mr-2">
                                    <div class="text-xs font-weight-bold text-info text-uppercase mb-1">You Do Not Have Any Notification</div>
                                    <div class="text-xs font-weight-bold text-info text-uppercase mb-1">Click Here To Find out Something Interesting</div>
                                </div>
                                <div class="col-auto">
                                    <i class="fas fa-clipboard-list fa-2x text-gray-300"></i>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% else %}
            {% for action in posttemplate_activities %}
                <div class="col-xl-3 col-md-6 mb-4">
                    <div class="card border-left-info shadow h-100 py-2">
                        <div class="card-body">
                            <div class="row no-gutters align-items-center">
                                <div class="col mr-2">
                                    <div class="text-xs font-weight-bold text-info text-uppercase mb-1" onclick="return false">{% display_action action %}</div>
                                </div>
                                <div class="col-auto">
                                    <i class="fas fa-clipboard-list fa-2x text-gray-300"></i>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
            {% endif %}
        </div>
    </div>


{% endblock %}


</html>

cityapp/templates/user/cards.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Comm - User</title>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.css">
    <!-- Custom fonts for this template-->
    <link href="{% static "vendor/fontawesome-free/css/all.min.css" %}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">

    <!-- Custom styles for this template-->
    <link rel="stylesheet" type="text/css" media="screen"
          href="https://cdnjs.cloudflare.com/ajax/libs/rateYo/2.3.1/jquery.rateyo.min.css">
    <link href="{% static "css/main.css" %}" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.js"></script>
    <script src="https://formbuilder.online/assets/js/form-builder.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/rateYo/2.3.1/jquery.rateyo.min.js"></script>
    <link href="{% static "css/sb-admin-2.min.css" %}" rel="stylesheet">
    <script type="text/javascript" charset="utf8"
            src="{% static "vendor/jquery/jquery.js" %}"></script>
    <script type="text/javascript" charset="utf8"
            src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.js"></script>
    {% block head_css %}
    {% endblock %}

</head>

<body id="page-top">

  <!-- Page Wrapper -->
  <div id="wrapper">

    <!-- Sidebar -->
    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

        <!-- Sidebar - Brand -->
        <a class="sidebar-brand d-flex align-items-center justify-content-center" href="/">
            <div class="sidebar-brand-icon rotate-n-15">
                <i class="fas fa-users"></i>
            </div>
            <div class="sidebar-brand-text mx-3">Comm <sup></sup></div>
        </a>

        <!-- Divider -->
        <hr class="sidebar-divider my-0">

        <!-- Nav Item - Dashboard -->
        <li class="nav-item active">
            <a class="nav-link" href="/">
                <i class="fas fa-fw fa-newspaper"></i>
                <span>Latest</span></a>
        </li>

        <!-- Divider -->
        <hr class="sidebar-divider">

        <!-- Heading -->
        <div class="sidebar-heading">
            Community
        </div>

        <!-- Nav Item - Pages Collapse Menu -->
        <li class="nav-item">
            <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo"
               aria-expanded="true" aria-controls="collapseTwo">
                <i class="fas fa-fw fa-user"></i>
                <span>My Cities</span>
            </a>
            <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
                <div class="bg-white py-2 collapse-inner rounded">
                    {% for community in communities %}
                        <a class="collapse-item"
                           href="{% url 'community:community-detail' community.id %}">{{ community.name|truncatechars:20 }}</a>
                    {% endfor %}
                </div>
            </div>
        </li>

        <!-- Nav Item - Utilities Collapse Menu -->
        <li class="nav-item">
            <a class="nav-link" href="{% url "city:list-city" %}">
                <i class="fas fa-fw fa-users"></i>
                <span>Cities</span></a>
        </li>


        <li class="nav-item">
            <a class="nav-link" href="{% url "city:create-city" %}">
                <i class="fas fa-fw fa-plus"></i>
                <span>Create City</span></a>
        </li>

        <!-- Sidebar Toggler (Sidebar) -->
        <div class="text-center d-none d-md-inline">
            <button class="rounded-circle border-0" id="sidebarToggle"></button>
        </div>

    </ul>
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

        <!-- Topbar -->
        <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                <!-- Sidebar Toggle (Topbar) -->
                <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                    <i class="fa fa-bars"></i>
                </button>

                <!-- Topbar Search -->

                <!-- Topbar Navbar -->
                <ul class="navbar-nav ml-auto">



                    <div class="topbar-divider d-none d-sm-block"></div>

                    <!-- Nav Item - User Information -->
                    <li class="nav-item dropdown no-arrow">
                        <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ user.username }}</span>
                            {#                            <img class="img-profile rounded-circle" src="https://source.unsplash.com/QAB-WJcbgJk/60x60">#}
                        </a>
                        <!-- Dropdown - User Information -->
                        <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                             aria-labelledby="userDropdown">

                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                                <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                Logout
                            </a>
                        </div>
                    </li>

                </ul>

            </nav>
        <!-- End of Topbar -->

        <!-- Begin Page Content -->
        <div class="container-fluid">

          <!-- Page Heading -->
          <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Cities</h1>
          </div>

          <div class="row">
              {% for city in cities %}

           <div class="col-xl-3 col-md-6 mb-4">
              <div class="card" style="width: 18rem;">
                    <img class="card-img-top" src="{{ city.image.url }}">
                    <div class="card-body">
                        <h5 class="card-title"><a href="{% url "city:detail-city" city.name %}"> {{ city.name }}</a></h5>
                        <p class="card-text">{{ city.country_name }}</p>
                    </div>
                 </div>
            </div>
            {% endfor %}

        </div>
        <!-- /.container-fluid -->

      </div>
      <!-- End of Main Content -->

      <!-- Footer -->
      <footer class="sticky-footer bg-white">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
            <span>Copyright &copy; Your Website 2019</span>
          </div>
        </div>
      </footer>
      <!-- End of Footer -->

    </div>
    <!-- End of Content Wrapper -->

  </div>
  <!-- End of Page Wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  <!-- Logout Modal-->
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
          <a class="btn btn-primary" href="login.html">Logout</a>
        </div>
      </div>
    </div>
  </div>

  <!-- Bootstrap core JavaScript-->
  <script src="vendor/jquery/jquery.min.js"></script>
  <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  <!-- Core plugin JavaScript-->
  <script src="vendor/jquery-easing/jquery.easing.min.js"></script>

  <!-- Custom scripts for all pages-->
  <script src="js/sb-admin-2.min.js"></script>

</body>

</html>

cityapp/templates/user/cities.html
{% extends "user/manager.html" %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
{% block wrapper %}
    <!-- Masthead -->
    <div class="row">
            {% for city in cities %}
                <div class="card col-lg-6" style="width: 18rem;">
                <div class="card-body">
                    <h5 class="card-title"><a href="{% url "city:detail-city" city.name %}"> {{ city.name }}</a></h5>
                    <p class="card-text">{{ city.country_name }}</p>
                    <p class="card-text">{{ city.geolocation }}</p>
                </div>
            </div>

            {% endfor %}

    </div>
{% endblock %}

</html>