cityapp/api/urls.py
from api.community_view import *
from api.user_views import *
from api.city_view import *
from django.urls import path
from rest_framework_swagger.views import get_swagger_view

schema_view = get_swagger_view(title='Community API')

app_name = "api"

urlpatterns = [
    path('users/register', UserRegistrationAPIView.as_view(), name="register"),
    path('users/login/', UserLoginAPIView.as_view(), name="login"),
    path('tokens/<key>/', UserTokenAPIView.as_view(), name="token"),

    path('community/swagger/', schema_view),

    path('community/create/', CreateCommunityAPIView.as_view(), name="create-community"),
    path('community/join/', JoinCommunityAPIView.as_view(), name="join-community"),
    path('community/search/', SearchCommunitiesAPIView.as_view(), name="search-community"),
    path('community/latest-posts/', UsersLatestPostsListAPIView.as_view(), name="latest-posts"),

    path('comment/create/', CommentCreateAPIView.as_view(), name="comment-create"),
    path('comment/create/<pk>/', CommentCreateAPIView_ForSpecificPost.as_view(), name="comment-create-post"),

    path('comment/list/', CommentListAPIView.as_view(), name="comment-list"),
    path('comment/list/<int:post_id>', CommentListAPIView_ForSpecificPost.as_view(), name="comment-list-specific"),

    path('comment/delete/<pk>/', CommentDeleteAPIView.as_view(), name="comment-delete"),
    path('comment/update/<pk>/', CommentUpdateAPIView.as_view(), name="comment-update"),
    path('search-city/', GetCityInformation.as_view(), name="search-city"),
    path('advanced-search/', AdvancedSearch.as_view(), name="advanced-search"),



]

cityapp/cityapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

api_urls = [
    path('community/', include('api.urls')),

]

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('community.urls')),
                  path('api/', include(api_urls)),
                  path('city/', include('city.urls')),
                  path('activity/', include('actstream.urls')),  # Activity Stream URL
                  path('api/annotations/', include('annotations.api.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cityapp/community/urls.py
from community import feeds
from community.views import *
from django.conf.urls import url
from django.urls import path

app_name = 'community'

urlpatterns = [
    path('', IndexTemplateView.as_view(), name="index"),
    path('search$', CommunitiesListTemplateView.as_view(), name="search-communities"),
    path('register', register_view, name="register"),
    path('login', login_view, name="login"),
    path('logout', logout_view, name="logout"),
    path('manager', CommunityLoginTemplateView.as_view(), name="manager"),
    path('dashboard', CommunityDashboardTemplateView.as_view(), name="dashboard"),
    path('communites-list', UserCommunitiesListTemplateView.as_view(), name="communities-list-user"),
    path('communities/<int:community_id>', CommunitiesDetailedTemplateView.as_view(), name="community-detail"),
    path('posts/<int:post_id>', PostsDetailedTemplateView.as_view(), name="post-detail"),
    path('data-types/<int:data_type_id>', DataTypeTemplateView.as_view(), name="data-type-detail"),
    path('communites-create', CreateCommunityTemplateView.as_view(), name="communities-create"),
    path('posts-create/<int:community_id>', CreatePostTemplateView.as_view(), name="posts-create"),
    path('data-type-create/<int:community_id>', CreateDataTypeTemplateView.as_view(), name="data-type-create"),
    path('join-community/<int:joined_community>', JoinCommunityTemplateView.as_view(), name="join-community"),
    path('joined-communites-list', JoinedCommunitiesListTemplateView.as_view(), name="joined-communities-list"),
    path('stream/json', feeds.UserJSONActivityFeed_V2.as_view(), name='actstream_feed_json'),
    path('stream/', notification, name='notification_combined'),
    path('stream/user/', notification_user, name='notification_user_all'),
    path('stream/community/', notification_community, name='notification_community_all'),
    path('stream/post', notification_post, name='notification_post_all'),
    path('stream/posttemplate', notification_posttemplate, name='notification_posttemplate_all'),
    path('followings/', followings, name='followings_combined'),
    path('followings/user/', followings_user, name='followings_user_all'),
    path('followings/community/', followings_community, name='followings_community_all'),
    path('followings/post/', followings_post, name='followings_post_all'),
    path('followings/posttemplate/', followings_post_template, name='followings_posttemplate_all'),
    path('followers/', followers, name='followers'),
    path('get-all-users', GetAllUsersTemplateView.as_view(), name="get-all-users"),
    path('flag-inappropriate', FlagPostAsInappropriate.as_view(), name="flag-post-inappropriate"),
    path('flag-appropriate', FlagPostAsAppropriate.as_view(), name="flag-post-appropriate"),
    path('user-posts/<int:user_id>', UserCreatedPostsTemplateView.as_view(), name="user-posts"),
    path('popularitems', PopularItems, name="popular_items"),
    path('popularitems/user', PopularItems_User, name="popular_items_user"),
    path('popularitems/community', PopularItems_Community, name="popular_items_community"),
    path('popularitems/posttemplate', PopularItems_PostTemplate, name="popular_items_posttemplate"),
    path('popularitems/post', PopularItems_Post, name="popular_items_post"),
    path('google587629e753de506e.html', GoogleVerify.as_view(), name="google-verify"),
    path('search', AdvancedSearchPage.as_view(), name="search-page"),
    path('delete-post/<int:post_id>', product_delete_rest_endpoint, name="delete-post"),
    # Override From <Actstream Url> In Order To Enable <User Stopped Following> Notification
    url(
        r'^unfollow/(?P<content_type_id>[^/]+)/(?P<object_id>[^/]+)/(?:(?P<flag>[^/]+)/)?$',
        follow_unfollow,
        {'do_follow': False},
        name='unfollow'
    ),
    url(
        r'^unfollow_all/(?P<content_type_id>[^/]+)/(?P<object_id>[^/]+)/(?:(?P<flag>[^/]+)/)?$',
        follow_unfollow,
        {'actor_only': False, 'do_follow': False},
        name='unfollow_all'
    )

]

cityapp/templates/_.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Community&Stuff</title>
    <link href="{% static "css/main.css" %}" rel="stylesheet">
</head>
<body>
<header>
    <div class="header">
        <div class="login"><a href="#">Login/Register</a></div>
    </div>
</header>

<div class="main">
    <div class="search">
        <input type="text" placeholder="Search..">
    </div>
    <div class="popular">
        <div class="popular-communities"><h3>Popular Communities</h3>
             <ul>
                {% for community in communities %}
                <li>{{community.name }}</li>
                {% endfor %}
            </ul>
        </div>
        <div class="popular-posts"><h3>Popular Posts</h3>
            <ul>
                {% for community in communities %}
                <li>{{community.name }}</li>
                {% endfor %}
            </ul>
        </div>
    </div>

</div>

<footer></footer>
</body>
</html>

cityapp/templates/google587629e753de506e.html
google-site-verification: google587629e753de506e.html

cityapp/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Comm</title>


    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.css">
    <!-- Bootstrap core CSS -->
    <link href="{% static "vendor/bootstrap/css/bootstrap.min.css" %}" rel="stylesheet">
    <!-- Custom fonts for this template -->
    <link href="{% static "vendor/fontawesome-free/css/all.min.css" %}" rel="stylesheet">
    <link href="{% static "vendor/simple-line-icons/css/simple-line-icons.css" %}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic"
          rel="stylesheet"
          type="text/css">
    <!-- Custom styles for this template -->
    <link href="{% static "css/landing-page.css" %}" rel="stylesheet">

    {% block scripts %}
        <script type="text/javascript" charset="utf8"
                src="{% static "vendor/jquery/jquery.js" %}"></script>
        <script type="text/javascript" src="{% static "js/main.js" %}"></script>
        <script type="text/javascript" charset="utf8"
                src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.js"></script>
    {% endblock %}


</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-light bg-light static-top">
    <div class="container">
        <a class="logo-sample" href="/">Comm</a>
        <a class="btn btn-primary" href="/login">Sign In</a>
    </div>
</nav>
{% block wrapper %}
    {% if user_success %}
            <div class="row">
                <div id="comm_alert" class="alert alert-success col-xl-12 col-md-12" role="note" style="text-align: center;">
                    User Registered successfully
                </div>
            </div>
        {% endif %}
    <!-- Masthead -->
    <header class="masthead text-white text-center">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-xl-9 mx-auto">
                    <h1 class="mb-5">Experiencing the City!</h1>
                </div>
                <div class="col-md-10 col-lg-8 col-xl-7 mx-auto">
                    <form onsubmit="">
                        <div class="form-row">
                            <div class="col-12 col-md-9 mb-2 mb-md-0">
                                <input id="search-input" type="Search" class="form-control form-control-lg"
                                       placeholder="Search">
                            </div>
                            <div class="col-12 col-md-3">
                                <button id="search" type="submit" class="btn btn-block btn-lg btn-primary">Search
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </header>
{% endblock %}
<!-- Footer -->
<footer class="footer bg-light">
    <div class="container">
        <div class="row">
            <div class="col-lg-6 h-100 text-center text-lg-left my-auto">
                <ul class="list-inline mb-2">
                    <li class="list-inline-item">
                        <a href="#">About</a>
                    </li>
                    <li class="list-inline-item">&sdot;</li>
                    <li class="list-inline-item">
                        <a href="#">Contact</a>
                    </li>
                    <li class="list-inline-item">&sdot;</li>
                    <li class="list-inline-item">
                        <a href="#">Terms of Use</a>
                    </li>
                    <li class="list-inline-item">&sdot;</li>
                    <li class="list-inline-item">
                        <a href="#">Privacy Policy</a>
                    </li>
                </ul>
                <p class="text-muted small mb-4 mb-lg-0">&copy; Comm 2020. All Rights Reserved.</p>
            </div>
            <div class="col-lg-6 h-100 text-center text-lg-right my-auto">

            </div>
        </div>
    </div>
</footer>

<!-- Bootstrap core JavaScript -->
<script src="vendor/jquery/jquery.min.js"></script>
<script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
<script>
    $('#search').click(function () {
        var search_comm = $("#search-input").val();
        var obj = {
            comm: search_comm
        };
        window.location.href = "{% url "community:search-communities" %}" + '?' + $.param(obj);
        return false;
    })
</script>


</body>

</html>

cityapp/templates/login.html
{% extends "index.html" %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin 2 - Login</title>

    <!-- Custom fonts for this template-->
    <link href="{% static "vendor/fontawesome-free/css/all.min.css" %}" rel="stylesheet" type="text/css">
    <link href="{% static "https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" %}"
          rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static "css/sb-admin-2.min.css" %}" rel="stylesheet">

</head>
{% block wrapper %}
    <body class="bg-gradient-primary">

    <div class="container">

        <!-- Outer Row -->
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            <div class="col-lg-6 d-none d-lg-block bg-login-image" style="background: url(https://i.iheart.com/v3/re/new_assets/5b3a6493c8de124da5d784aa);
background-position: center;
background-size: cover;"></div>
                            <div class="col-lg-6">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h1 class="h4 text-gray-900 mb-4">Welcome Back!</h1>
                                    </div>
                                    <form class="user" action="{% url "community:manager" %}" method="post">
                                        <div class="form-group">
                                            <input name="username" type="username" class="form-control form-control-user"
                                                   id="exampleInputEmail" aria-describedby="emailHelp"
                                                   placeholder="Enter Username">
                                        </div>
                                        <div class="form-group">
                                            <input name="password" type="password" class="form-control form-control-user"
                                                   id="exampleInputPassword" placeholder="Password">
                                        </div>
                                        <div class="form-group">
                                            <div class="custom-control custom-checkbox small">
                                                <input type="checkbox" class="custom-control-input" id="customCheck">
                                                <label class="custom-control-label" for="customCheck">Remember
                                                    Me</label>
                                            </div>
                                        </div>
                                        <button class="btn btn-primary btn-user btn-block">
                                            Login
                                        </button >
                                    </form>
                                    <hr>
                                    <div class="text-center">
                                        <a class="small" href="forgot-password.html">Forgot Password?</a>
                                    </div>
                                    <div class="text-center">
                                        <a class="small" href="register">Create an Account!</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="{% static "vendor/jquery/jquery.min.js" %}"></script>
    <script src="{% static "vendor/bootstrap/js/bootstrap.bundle.min.js" %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static "vendor/jquery-easing/jquery.easing.min.js" %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static "js/sb-admin-2.min.js" %}"></script>

    </body>
{% endblock %}
</html>

cityapp/templates/register.html
{% extends "index.html" %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Register</title>

    <link href="{% static "vendor/fontawesome-free/css/all.min.css" %}" rel="stylesheet" type="text/css">
    <link href="{% static "https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" %}"
          rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static "css/sb-admin-2.min.css" %}" rel="stylesheet">

    <!-- Custom fonts for this template-->


</head>
{% block wrapper %}
    <body class="bg-gradient-primary">

    <div class="container">

        <div class="card o-hidden border-0 shadow-lg my-5">
            <div class="card-body p-0">
                <!-- Nested Row within Card Body -->
                <div class="row">
                    <div class="col-lg-5 d-none d-lg-block bg-register-image" style="background: url(https://avatars.mds.yandex.net/get-pdb/1043766/36d2563c-1484-41fb-bb35-04207b5a0444/s1200?webp=false);
background-position: center;
background-size: cover;"></div>
                    <div class="col-lg-7">
                        <div class="p-5">
                            <div class="text-center">
                                <h1 class="h4 text-gray-900 mb-4">Create an Account!</h1>
                            </div>
                            <form class="user" action="{% url "api:register" %}" method="post">{% csrf_token %}
                                <div class="form-group row">
                                    <div class="col-sm-6 mb-3 mb-sm-0">
                                        <input type="text" class="form-control form-control-user" id="username"
                                               name="username"
                                               placeholder="Username">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <input type="email" class="form-control form-control-user" id="email" name="email"
                                           placeholder="Email Address">
                                </div>
                                <div class="form-group row">
                                    <div class="col-sm-6 mb-3 mb-sm-0">
                                        <input type="password" class="form-control form-control-user"
                                               id="password" name="password" placeholder="Password">
                                    </div>
                                    <div class="col-sm-6">
                                        <input type="password" class="form-control form-control-user"
                                               id="confirm_password" name="confirm_password"
                                               placeholder="Repeat Password">
                                    </div>
                                </div>
                                <button class="btn btn-primary btn-user btn-block">
                                    Register Account
                                </button>
                                <hr>
                            </form>

                            <div class="text-center">
                                <a class="small" href="login">Already have an account? Login!</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>


    <script src={% static "vendor/jquery/jquery.min.js" %}></script>
    <script src={% static "vendor/bootstrap/js/bootstrap.bundle.min.js" %}></script>

    <!-- Core plugin JavaScript-->
    <script src={% static "vendor/jquery-easing/jquery.easing.min.js" %}></script>

    <!-- Custom scripts for all pages-->
    <script src={% static "js/sb-admin-2.min.js" %}></script>
    <!-- Bootstrap core JavaScript-->
    </body>

{% endblock %}

</html>

cityapp/templates/search.html
{% extends "index.html" %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
{% block wrapper %}
    <!-- Masthead -->
    <div class="col-md-10 col-lg-10 col-xl-10 mx-auto">
        <table id="table_id" class="display" style="width: 100%;">
            <thead>
            <tr>
                <th>Community Name</th>
                <th>Tags</th>
                <th>#Users</th>
                <th>Created By</th>
                <th>Join</th>

            </tr>
            </thead>
            <tbody>
            {% for comm in comms %}
                <tr>
                    <td>{{ comm.name }}</td>
                    <td>{% for tag in comm.tags.all %}{{ tag.name }} {% endfor %}</td>
                    <td>{{ comm.joined_users.count }}</td>
                    <td>{{ comm.created_by.username }}</td>
                     <td><button onclick="location.href='login'">Login</button></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}
<script>
    $(document).ready(function () {
        $('#table_id').DataTable();
    });
</script>


</html>